editor = "code"

[db-config]
username = "root"
password = "root"
net = "tcp"
address = "127.0.0.1:3306"
db-name = "trackers"
table-name = "habit_tracker"

[paths]
tracker-path = "/Users/harshitcd/.config/habit_tracker/tracker.toml"
